apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: payment
  app.kubernetes.io/component: payment
  app.kubernetes.io/instance: payment
  app.kubernetes.io/part-of: payment
  app.openshift.io/runtime: golang

resources:
- deployment.yaml
- service.yaml
- route.yaml

images:
- name: payment
  newName: quay.io/calopezb/payment-microservice
  newTag: 1.0.2