apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    scaledobject.keda.sh/name: keda-scaled
  name: payment-scaler
  namespace: payment
spec:
  maxReplicaCount: 3
  minReplicaCount: 1
  pollingInterval: 5
  scaleTargetRef:
    kind: Deployment
    name: payment 
  triggers:
  - authenticationRef:
      name: keda-trigger-auth-prometheus
    metadata:
      authModes: bearer
      metricName: http_requests_total
      namespace: payment
      query: rate(http_requests_total{job="payment"}[1m])
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      threshold: "1"
    type: prometheus