kind: KedaController
apiVersion: keda.sh/v1alpha1
metadata:
  name: keda-payment
  namespace: openshift-keda
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  watchNamespace: 'payment'
  operator:
    logLevel: info 
    logEncoder: console 
  metricsServer:
    logLevel: '0' 
  serviceAccount: {}