apiVersion: v1
kind: Secret
metadata:
  name: thanos-token
  namespace: payments
  annotations:
    kubernetes.io/service-account.name: thanos 
    argocd.argoproj.io/sync-wave: "3"
type: kubernetes.io/service-account-token