apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payment-thanos-metrics-reader
  namespace: payments
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch