apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-metrics-reader 
  namespace: payment
  annotations:
    argocd.argoproj.io/sync-wave: "4"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: payment-thanos-metrics-reader
subjects:
- kind: ServiceAccount
  name: thanos 
  namespace: payment