apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
  namespace: payment
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretTargetRef: 
  - parameter: bearerToken 
    name: thanos-token 
    key: token 
  - parameter: ca
    name: thanos-token
    key: ca.crt