apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: eda-routing
  namespace: payment
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  route:
    receiver: 'webhook'
    groupBy: ['alertname']
    groupInterval: 5s
    groupWait: 1s
    repeatInterval: 1h
  receivers:
    - name: 'webhook'
      webhookConfigs:
      - url: http://eda-routing.aap.svc.cluster.local:5000/endpoint