apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-payment-monitor
  namespace: payment
spec:
  endpoints:
  - interval: 5s
    port: 8080-tcp 
    scheme: http
  selector: 
    matchLabels:
      app: payment