- name: Include vars
  ansible.builtin.include_vars:
    file: custom.yaml

# - name: Create Servicenow user
#   ansible.builtin.include_tasks:
#     file: servicenow.yaml

- name: Configure Ansible Controller
  ansible.builtin.include_role:
    name: ansible_automation_platform.casc.controller
  vars:
    installation_type: ocp
    controller_vars_dir: casc/vars/controller

- name: Configure Ansible Eda
  ansible.builtin.include_role:
    name: ansible_automation_platform.casc.eda
  vars:
    installation_type: ocp
    eda_vars_dir: casc/vars/eda
