
---
- name: Reset Payment Application
  hosts: localhost
  gather_facts: true
  vars:
    repository: "{{ lookup('env', 'GITEA_HOST') }}/gitea/payment-deploy.git"
  tasks:

    - name: Remove Payment application
      kubernetes.core.k8s:
        state: absent
        api_version: argoproj.io/v1alpha1
        kind: Application
        namespace: openshift-gitops
        name: payment
        wait: true
        force: true

    - name: Remove Payment Physical Volume Claim
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: payment
        name: payment
        wait: false
        force: true

    - name: Remove Payment Physical Volume
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: PersistentVolume
        namespace: payment
        name: payment
        wait: false
        force: true

    - name: Get current date
      ansible.builtin.set_fact:
        operation_time: "{{ ansible_date_time.epoch }}"

    - name: Clone Configuration Repository
      ansible.builtin.include_role:
        name: demos.utils.git
      vars:
        git_repository: "{{ repository }}"
        git_directory: "/tmp/{{ operation_time }}"
        git_operation: clone
      register: git_result

    - name: Modify PVC
      ansible.builtin.lineinfile:
        state: present
        backrefs: true
        path: "/tmp/{{ operation_time }}/pvc.yaml"
        regexp: '^(\s*)name:.*'
        line: '\1name: payment-{{ operation_time }}'

    - name: Replace volumeMounts name
      ansible.builtin.replace:
        path: "/tmp/{{ operation_time }}/deployment.yaml"
        regexp: '^(\s*- name: )\S+(\s*\n\s*mountPath: /mnt)'
        replace: '\1payment-{{ operation_time }}\2'

    - name: Replace volumes name
      ansible.builtin.replace:
        path: "/tmp/{{ operation_time }}/deployment.yaml"
        regexp: '^(\s*- name: )\S+(\s*\n\s*persistentVolumeClaim:)'
        replace: '\1payment-{{ operation_time }}\2'

    - name: Replace claimName
      ansible.builtin.replace:
        path: "/tmp/{{ operation_time }}/deployment.yaml"
        regexp: '^(\s*claimName: )\S+'
        replace: '\1payment-{{ operation_time }}'

    - name: Commit configuration to repository
      ansible.builtin.include_role:
        name: demos.utils.git
      vars:
        git_operation: push
        git_repository: "{{ repository }}"
        git_directory: "/tmp/{{ operation_time }}"
        git_email: "{{ lookup('env', 'GITEA_USERNAME') }}@redhat.com"
        git_user: "{{ lookup('env', 'GITEA_USERNAME') }}"
        git_message: "Reset Application"
      register: git_result

    - name: Create Payment applications
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: payment
            namespace: openshift-gitops
          spec:
            project: default
            source:
              repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea/payment-deploy
              targetRevision: master
              path: .
            destination:
              server: https://kubernetes.default.svc
              namespace: payment
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        wait: true

    - name: Get Alarms Silences
      kubernetes.core.k8s_exec:
        namespace: openshift-monitoring
        pod: alertmanager-main-0
        command: amtool silence --alertmanager.url http://localhost:9093 -o json
      register: alarms_ids

    - name: Get Silences IDs
      ansible.builtin.set_fact:
        ids: "{{ alarms_ids.stdout | from_json }}"

    - name: Restore Alarms
      kubernetes.core.k8s_exec:
        namespace: openshift-monitoring
        pod: alertmanager-main-0
        command: "amtool silence expire {{ item }} --alertmanager.url http://localhost:9093"
      loop: "{{ ids | map(attribute='id') | list }}"

