---
- name: Synchronize ArgoCD - Only for demo Purpose
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Get Argocd Token
      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'ARGOCD_HOST') }}/api/v1/session"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
        body:
          username: "{{ lookup('ansible.builtin.env', 'ARGOCD_USERNAME') }}"
          password: "{{ lookup('ansible.builtin.env', 'ARGOCD_PASSWORD') }}"
        status_code: 200
        force_basic_auth: true
        validate_certs: false
      register: argocd_token

    - name: Synchronize APP
      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'ARGOCD_HOST') }}/api/v1/applications/payment/sync?project=default"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ argocd_token.json.token }}"
        body:
          username: "{{ lookup('ansible.builtin.env', 'ARGOCD_USERNAME') }}"
          password: "{{ lookup('ansible.builtin.env', 'ARGOCD_PASSWORD') }}"
        status_code: 200
        validate_certs: false
