---
- name: Add information to Servicenow Ticket
  hosts: localhost
  gather_facts: true
  tasks:

    - name: Add information to Servicenow Incident
      servicenow.itsm.api:
        resource: incident
        action: patch
        sys_id: "{{ record.sys_id }}"
        data:
          state: 3
          incident_state: 3
          number: "{{ record.task_effective_number }}"
          close_code: "Resolved by Event_driven Ansible"
          close_notes: "Restarted Nginx Container"
          caller: "admin"
