---
- name: Add information to Servicenow Ticket
  hosts: localhost
  gather_facts: true
  tasks:

    - name: Add information to Servicenow Incident
      servicenow.itsm.api:
        resource: incident
        action: patch
        sys_id: "{{ ansible_eda.event.sys_id }}"
        data:
          state: 3
          incident_state: 3
          number: "{{ incident_id }}"
          work_notes: "The max number of replicas for the app Payment, has been increased to {{ new_replicas }}. Please, check "
          caller: "admin"
