sn_host: "{{ lookup('ansible.builtin.env', 'SERVICENOW_HOST') }}"
sn_username: "{{ lookup('ansible.builtin.env', 'SERVICENOW_USER') }}"
sn_password: "{{ lookup('ansible.builtin.env', 'SERVICENOW_PASS') }}"

gitea_host: "https://gitea-{{ gitea.namespace }}.apps.{{ gitea.ocp_domain }}"
gitea_username: "gitea"
gitea_password: "openshift"

rhn_username: "{{ lookup('community.general.bitwarden_secrets_manager', '21d8d4ff-9191-402c-813a-b26c012837f3').value }}"
rhn_password: "{{ lookup('community.general.bitwarden_secrets_manager', '69b6ba85-0169-4c30-b524-b26c01285afd').value }}"
rhn_pool_id: "{{ lookup('community.general.bitwarden_secrets_manager', '4d4c5bf5-a9eb-4832-8a45-b26c01291c55').value }}"

quay_username: "{{ lookup('community.general.bitwarden_secrets_manager', '82f4b092-50fb-4138-bed9-b26e00ce0298').value }}"
quay_password: "{{ lookup('community.general.bitwarden_secrets_manager', '031b3102-55a9-4bf0-ba02-b26e00ce1a15').value }}"

argocd_host: "{{ lookup('community.general.bitwarden_secrets_manager', '18f3b1df-daef-42e6-9abd-b26e0102dc8d').value }}"
argocd_user: "{{ lookup('community.general.bitwarden_secrets_manager', 'd7a858c1-8893-4ca3-9437-b26e0102b025').value }}"
argocd_password: "{{ lookup('community.general.bitwarden_secrets_manager', 'c58b62d9-028b-49bf-99cf-b26e0102c480').value }}"

openshift_host: "{{ lookup('community.general.bitwarden_secrets_manager', '2641e11b-7bb6-4b40-9d8b-b26e0103b98a').value }}"
openshift_token: "{{ lookup('community.general.bitwarden_secrets_manager', '1dcdf6b2-d5e7-4d62-9973-b26e0103da88').value }}"